# Generated by Django 3.0 on 2022-02-10 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_restful_main', '0002_auto_20220210_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
    ]
