# Generated by Django 3.0 on 2022-02-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0002_auto_20220207_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
