# Generated by Django 3.0 on 2022-02-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0003_task_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='successed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
