# Generated by Django 3.0 on 2022-02-09 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0004_task_successed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='successed_at',
            new_name='succeed_at',
        ),
    ]
