# Generated by Django 3.0 on 2022-02-09 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0005_auto_20220209_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='succeed_at',
        ),
    ]
