# Generated by Django 3.0 on 2022-02-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0006_remove_task_succeed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
