# Generated by Django 3.0 on 2022-02-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0008_task_succeed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='succeed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
