# Generated by Django 3.0 on 2022-02-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_main', '0009_auto_20220209_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='succeed_at',
        ),
    ]
